### ISSUE TITLE
请问是否有svg或>=200px的logo可以提供？

### ISSUE THREAD

**Issue by xlch88** [hykilpikonna/OneAmongUs.Web#11]
目前正在做一个跨性别相关的导航网站，在整理网站信息时，没有在源代码和网站上找到贵站较为清楚的logo。

请问是否能提供一个svg或者是>=200px的png图像呢？

**Comment by sauricat** [comment]
[已添加](https://github.com/hykilpikonna/OneAmongUs.Web/blob/master/public/favicon-large.png)，请查收。
